### ISSUE TITLE
`.properties` file should not be needed to compile a `dust` template without `<pre>` tags.

### ISSUE THREAD

**Issue by pvenkatakrishnan** [krakenjs/grunt-localizr#9]

**Comment by aredridel** [comment]
Good call.

**Comment by aredridel** [comment]
What error do you get when this happens?

**Comment by pvenkatakrishnan** [comment]
it just bypasses and moves on to compile others is what i hear from the project that reported the bug.

**Comment by aredridel** [comment]
Hmm. According to the source, it should handle this fine. There's a path for handling bundles with no properties files.

**Comment by pvenkatakrishnan** [comment]
interesting, i haven't tried it out myself. Thats what i thought too. maybe there is an edge case that is not fully explained from that email thread. let me ask him to list the steps to repro.

**Comment by aredridel** [comment]
Awesome.

**Comment by pvenkatakrishnan** [comment]
here is a sample app that just compiles fine when no pre tags.

**Comment by aredridel** [comment]
Yeah, that works for me too.

**Comment by pvenkatakrishnan** [comment]
I suspect the actual issue is https://github.com/krakenjs/grunt-localizr/issues/7 coz i do see multiple dust files with the same name in various `dirs`.

**Comment by aredridel** [comment]
This makes a lot of sense.

**Comment by seanzarrin** [comment]
We have been experiencing a similar issue (missing properties files causes the relative dust file not to be built at all). I may be wrong, but it may be due to the map function called here https://github.com/krakenjs/grunt-localizr/blob/88ac47659db2f7e38a8e86790bae9595eaa5e924/tasks/index.js#L102.

I think this assumes that the property file structure is the same for each locale, but if a property file is only present for one locale and not for others, processWhenNoBundles will not be called.

**Comment by aredridel** [comment]
Yes. The assumption is that if a template is localized, the content to localize it should be present. Is there a case for you where this is not true?

(it should error, though, I think, not silently not work)

**Comment by pvenkatakrishnan** [comment]
@seanzarrin a `.propertes` file for any locale corresponding to a specific `dust` file need to have similar structure. processWhenNoBundles is called only for dust files with no `pre` tags in them. How can we properly compile a `dust` file which has `pre` tags BUT no content for it. That is not a desirable behavior, no?

**Comment by pvenkatakrishnan** [comment]
This specific issue has been debugged and resolved.  `0.2.1` was published with the fixes.

**Comment by seanzarrin** [comment]
Yes, I agree. We were seeing this issue when a file has no <code>pre</code> tags, but there is a <code>.properties</code> file for it only in one locale. Clearly this <code>.properties</code> isn't needed, however the rest of the partials would not build because a <code>.properties</code> file is expected. Perhaps I was using an outdated version, but @aredridel would an error be thrown in that case?

**Comment by aredridel** [comment]
No, and arguably it should go through the non-localized path and not error and work.

**Comment by seanzarrin** [comment]
That is the behavior I would expect, too. I still see the issue in <code>0.2.1</code>.

**Comment by pvenkatakrishnan** [comment]
agree, will work on a fix for this. Thanks @seanzarrin  for bringing this up!

**Comment by pvenkatakrishnan** [comment]
do you mind if i create a different issue capturing this specific case ? Cause the original issue was about similarly named files causing an issue.

**Comment by seanzarrin** [comment]
New issue created https://github.com/krakenjs/localizr/issues/13. Thank you both!

**Comment by seanzarrin** [comment]
haha oops, wrong repo. here it is https://github.com/krakenjs/grunt-localizr/issues/15

**Comment by pvenkatakrishnan** [comment]
ok closing this one out.
